### ISSUE TITLE
Is there any chance to use cocoapods as a package manager?

### ISSUE THREAD

**Issue by melochale** [strongloop-community/loopback-sdk-ios#55]
Is there any chance to use cocoapods as a package manager? It will be more convenient  if using cocoapods to manage this project.

**Comment by lennartstolz** [comment]
Have you tried: 

```
pod 'LoopBack'

**Comment by lennartstolz** [comment]
Full (and hopefully more helpful): 

I currently use this fork and commit of @hideya until his pull request is not reviewed: 

```
pod 'LoopBack', :git => 'https://github.com/hideya/loopback-sdk-ios', :commit => '0ac46fa'
```

2) After *pod install* you'll run into an issue in LBFile.m That's not good, but until my pull request is reviewed "normal".

You could easily fix this by hand with adding the following code into the top of the LBFile.m:

```objectivec
#if TARGET_OS_IPHONE
#import <MobileCoreServices/MobileCoreServices.h>
#endif
```

After this, it should work like charm.

**Comment by melote** [comment]
thanks very much.  I can't find any official cocoapods docs of loopback-ios-sdk, so I thought there's no documentation about it, my bad.

**Comment by hideya** [comment]
Just a quick note -- as @lennartstolz's PR #46 has been merged, the master is now ready for cocoapods :-)

**Comment by kexoth** [comment]
But still it would be nice if the owners of the LoopBack SDK will publish it on CocoaPods :+1:

**Comment by hideya** [comment]
+1
@bajtos is working on it.

**Comment by kgoedecke** [comment]
I wrote a quick tutorial on how to use LoopBack SDK in Swift with Cocoapods http://kevingoedecke.me/2015/12/11/using-loopback-ios-sdk-with-cocoapods-in-swift/
